require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.5
  RSpec:
    Patterns:
    - '.+'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: true
  EnforcedStyle: assign_inside_condition

Style/RegexpLiteral:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/**/*'
