version: '3'
services:
  app:
    build: .
    command: rails s -b 0.0.0.0
    ports:
      - 80:3000
      - 3035:3035
    volumes:
      - .:/var/www/photos
    # links:
    #   - database
    env_file:
      - .env
  # database:
  #   image: neo4j:latest
volumes:
  photos-data:
